### ISSUE TITLE
Compatibility issue related to working with MIUI-Flash-Freely

### ISSUE THREAD

**Issue by deepanshpandey** [ianchb/MIUI-AOD-Freely#2] opened 2023-02-18 09:48 UTC
After failing multiple times to use miui aod freely on 
device: Xiaomi 11 lite ne 5g
codename: lisa , Android Version: 13
miui version: 14.0.3 india stable
I found that the device Features file in "/product/etc/device_features" is read only,
it would be really helpful if you provide a fix for it

**Comment by ianchb** [comment] 2023-02-18 10:17
Did you mean you cannot edit the lisa.xml file in the system manually? If so it's an expected behavior. Search for "is_only_support_keycode_goto", if it's already set to false, then it should work.

**Comment by deepanshpandey** [comment] 2023-02-18 10:22
it is set to true even after flashing the module

**Comment by ianchb** [comment] 2023-02-18 10:29
Please check if a .xml file exists in this path:
/data/adb/modules/MIUI_AOD_Freely/system/product/etc/device_features/
If not, uninstall the module and re-install it.
Also, please tell me your module version, or give me a screenshot in your Magisk Manager.

**Comment by deepanshpandey** [comment] 2023-02-18 12:43
![Screenshot_2023-02-18-18-12-28-025_io github huskydg magisk](https://user-images.githubusercontent.com/60426924/219866412-ff38a714-2ee3-4574-83ac-70a5b488c432.jpg)
the files does exist and also I have attached the screenshots
![Screenshot_2023-02-18-18-12-12-549_com cxinventor file explorer](https://user-images.githubusercontent.com/60426924/219866424-49f2df08-7775-48a5-b82a-3e820639ce9e.jpg)

![Screenshot_2023-02-18-18-12-02-077_com cxinventor file explorer](https://user-images.githubusercontent.com/60426924/219866430-b66e3687-3182-4e04-a8b5-1bdeafd1cae5.jpg)

**Comment by deepanshpandey** [comment] 2023-02-18 12:46
I am also attaching about page just in case if it's needed
![Screenshot_2023-02-18-18-15-07-797_com android settings](https://user-images.githubusercontent.com/60426924/219866602-6cb82d11-c099-4ed7-a0d3-d43452e8af0e.jpg)

**Comment by ianchb** [comment] 2023-02-18 12:47
So is the "is_only_support_keycode_goto" set to true in /data/adb/modules/MIUI_AOD_Freely/lisa.xml ?
If so please attach that file here.

**Comment by deepanshpandey** [comment] 2023-02-18 12:49
no it is set to false in data/adb/modules.... folder 
still there's the 10s limit for the AOD
### 
![Screenshot_2023-02-18-18-19-58-351_com miui aod](https://user-images.githubusercontent.com/60426924/219866739-b8f32aff-55be-4cd6-ba6e-a266d8034f71.jpg)

**Comment by ianchb** [comment] 2023-02-18 12:53
I've noticed that you are also using MIUI-Flash-Freely. Does it work?

**Comment by ianchb** [comment] 2023-02-18 13:19
I've noticed that you are also using MIUI-Flash-Freely. Does it work?

UPDATE: I know the situation now. The problem was caused by a conflict which happens when AOD-Freely and Flash-Freely are both enabled. It will be fixed soon.

**Comment by deepanshpandey** [comment] 2023-02-18 13:21
yup flash freely is working 
and also thankyou so much for sorting this out this quickly...
btw nice talking to ya

**Comment by ianchb** [comment] 2023-02-18 15:52
Probably solved in #3. Check for update in your Magisk manager.
Please let me know if the issue persists.

**Closed as completed by ianchb** 2023-02-18 15:52 UTC
Labels: bug
